apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: demo-gke
  git:
    syncRepo: https://github.com/yangwhale/kcc_demo.git
    syncBranch: master
    secretType: none
    policyDir: "src/acm/dns"
  configConnector:
    enabled: true
  policyController:
    enabled: false
