apiVersion: v1
kind: Secret
metadata:
  name: wordpress-cloudsql-db-credentials
stringData:
  projectId: chris-demo-258505
  username: wordpress
  password: change-me
  connectionName: us-central1:wp-db-01
