apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: chrisgcp02-com
  annotations:
      cnrm.cloud.google.com/deletion-policy: abandon
spec:
  dnsName: "chrisgcp02.com."
