apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: spanner-coffee-sa-wi-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: spanner-coffee-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:chris-demo-258505.svc.id.goog[default/spanner-coffee-ksa-wi]
