apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: coffee-external
  labels:
    app: coffee
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: web
      targetPort: 8080
      protocol: TCP
  selector:
    app: coffee
